Repository italoaugusto/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#2 Título: integrar requisitos v1.0
  docs/requisitos.md
  requisitos.md
Labels: Análise

#4 Integrar arquitetura v1.0
  docs/arquitetura.md
Labels: Arquitetura

#6 Integrar Programação v1.0
  src/jogodavelha.py
Labels: Programação

#8 Integrar teste v1.0
  src/testes_inic.py
  src/testes_jogar.py
Labels: Testes

#9 Gerar release v1.0
  docs/arquitetura.md
  docs/requisitos.md
  requisitos.md
  src/jogodavelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: Operação

#13 Integrar Arquitetura V.1.1
  docs/Arquitetura1.md
Labels: Arquitetura

#15 Integrar Implementação v1.1
  src/tabuleiro1.1.py
Labels: Programação

#17 Integrar testes V1.1
  src/jogotabuleiro v1.1.md
  src/testetabuleiro v1.1.md
Labels: Testes
